- hosts: workers
  tasks:
          - name: Install java
            become: yes
            apt:
                name: openjdk-8-jre
                state: present
          - name: Change java version from 11 to 8
            become: yes
            community.general.alternatives:
                name: java
                path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
