- hosts: workers
  tasks:
          - name: Remove scala
            become: yes
            yum:
                name: scala-library
                state: absent
          - name: Remove scala
            become: yes
            yum:
                    name: scala
                    state: absent
          - name: Copy scala deb to workers
            copy: src=/home/hadoop/scala-2.12.8.rpm dest=/home/hadoop/
          - name: Install scala package
            become: yes
            yum:
                    name: /home/hadoop/scala-2.12.8.rpm
                    state: present








